In [1]:
import pandas as pd

In [4]:
games_df18 = pd.read_csv(r'C:\Users\pad39\Downloads\inclass-data-main\inclass-data-main\2018-games.csv')

In [6]:
games_df18.head()

,Unnamed: 0,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,...,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
0,16196,2019-06-13,41800406,Final,1610612744,1610612761,2018,1610612744,110.0,0.488,...,28.0,42.0,1610612761,114.0,0.476,0.793,0.394,25.0,39.0,0
1,16197,2019-06-10,41800405,Final,1610612761,1610612744,2018,1610612761,105.0,0.447,...,19.0,43.0,1610612744,106.0,0.463,0.714,0.476,27.0,37.0,0
2,16198,2019-06-07,41800404,Final,1610612744,1610612761,2018,1610612744,92.0,0.449,...,26.0,42.0,1610612761,105.0,0.419,0.958,0.313,22.0,39.0,0
3,16199,2019-06-05,41800403,Final,1610612744,1610612761,2018,1610612744,109.0,0.396,...,25.0,41.0,1610612761,123.0,0.524,0.952,0.447,30.0,40.0,0
4,16200,2019-06-02,41800402,Final,1610612761,1610612744,2018,1610612761,104.0,0.372,...,17.0,49.0,1610612744,109.0,0.463,0.870,0.382,34.0,42.0,0

In [10]:
games_df19 = pd.read_csv(r'C:\Users\pad39\Downloads\inclass-data-main\inclass-data-main\2019-games.csv')

In [11]:
games_df = pd.concat([games_df18, games_df19])

In [12]:
games_df.drop(columns='Unnamed: 0', inplace=True)
games_df.head(2)

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,...,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
0,2019-06-13,41800406,Final,1610612744,1610612761,2018,1610612744,110.0,0.488,0.700,...,28.0,42.0,1610612761,114.0,0.476,0.793,0.394,25.0,39.0,0
1,2019-06-10,41800405,Final,1610612761,1610612744,2018,1610612761,105.0,0.447,0.778,...,19.0,43.0,1610612744,106.0,0.463,0.714,0.476,27.0,37.0,0

In [16]:
teams_df = pd.read_csv(r'C:\Users\pad39\Downloads\inclass-data-main\inclass-data-main\teams.csv')
teams_df

,LEAGUE_ID,TEAM_ID,MIN_YEAR,MAX_YEAR,ABBREVIATION,NICKNAME,YEARFOUNDED,CITY,ARENA,ARENACAPACITY,OWNER,GENERALMANAGER,HEADCOACH,DLEAGUEAFFILIATION
0,0,1610612737,1949,2019,ATL,Hawks,1949,Atlanta,State Farm Arena,18729.0,Tony Ressler,Travis Schlenk,Lloyd Pierce,Erie Bayhawks
1,0,1610612738,1946,2019,BOS,Celtics,1946,Boston,TD Garden,18624.0,Wyc Grousbeck,Danny Ainge,Brad Stevens,Maine Red Claws
2,0,1610612740,2002,2019,NOP,Pelicans,2002,New Orleans,Smoothie King Center,NaN,Tom Benson,Trajan Langdon,Alvin Gentry,No Affiliate
3,0,1610612741,1966,2019,CHI,Bulls,1966,Chicago,United Center,21711.0,Jerry Reinsdorf,Gar Forman,Jim Boylen,Windy City Bulls
4,0,1610612742,1980,2019,DAL,Mavericks,1980,Dallas,American Airlines Center,19200.0,Mark Cuban,Donnie Nelson,Rick Carlisle,Texas Legends
5,0,1610612743,1976,2019,DEN,Nuggets,1976,Denver,Pepsi Center,19099.0,Stan Kroenke,Tim Connelly,Michael Malone,No Affiliate
6,0,1610612745,1967,2019,HOU,Rockets,1967,Houston,Toyota Center,18104.0,Tilman Fertitta,Daryl Morey,Mike D'Antoni,Rio Grande Valley Vipers
7,0,1610612746,1970,2019,LAC,Clippers,1970,Los Angeles,Staples Center,19060.0,Steve Ballmer,Michael Winger,Doc Rivers,Agua Caliente Clippers of Ontario
8,0,1610612747,1948,2019,LAL,Lakers,1948,Los Angeles,Staples Center,19060.0,Jerry Buss Family Trust,Rob Pelinka,Frank Vogel,South Bay Lakers
9,0,1610612748,1988,2019,MIA,Heat,1988,Miami,AmericanAirlines Arena,19600.0,Micky Arison,Pat Riley,Erik Spoelstra,Sioux Falls Skyforce
10,0,1610612749,1968,2019,MIL,Bucks,1968,Milwaukee,Fiserv Forum,17500.0,Wesley Edens &Â Marc Lasry,Jon Horst,Mike Budenholzer,Wisconsin Herd
11,0,1610612750,1989,2019,MIN,Timberwolves,1989,Minnesota,Target Center,19356.0,Glen Taylor,Scott Layden,Ryan Saunders,Iowa Wolves
12,0,1610612751,1976,2019,BKN,Nets,1976,Brooklyn,Barclays Center,NaN,Joe Tsai,Sean Marks,Kenny Atkinson,Long Island Nets
13,0,1610612752,1946,2019,NYK,Knicks,1946,New York,Madison Square Garden,19763.0,Cablevision (James Dolan),Steve Mills,David Fizdale,Westchester Knicks
14,0,1610612753,1989,2019,ORL,Magic,1989,Orlando,Amway Center,0.0,Rick DeVos,John Hammond,Steve Clifford,Lakeland Magic
15,0,1610612754,1976,2019,IND,Pacers,1976,Indiana,Bankers Life Fieldhouse,18345.0,Herb Simon,Kevin Pritchard,Nate McMillan,Fort Wayne Mad Ants
16,0,1610612755,1949,2019,PHI,76ers,1949,Philadelphia,Wells Fargo Center,NaN,Joshua Harris,Elton Brand,Brett Brown,Delaware Blue Coats
17,0,1610612756,1968,2019,PHX,Suns,1968,Phoenix,Talking Stick Resort Arena,NaN,Robert Sarver,James Jones,Monty Williams,Northern Arizona Suns
18,0,1610612757,1970,2019,POR,Trail Blazers,1970,Portland,Moda Center,19980.0,Paul Allen,Neil Olshey,Terry Stotts,No Affiliate
19,0,1610612758,1948,2019,SAC,Kings,1948,Sacramento,Golden 1 Center,17500.0,Vivek Ranadive,Vlade Divac,Luke Walton,Stockton Kings
20,0,1610612759,1976,2019,SAS,Spurs,1976,San Antonio,AT&T Center,18694.0,Peter Holt,Brian Wright,Gregg Popovich,Austin Spurs
21,0,1610612760,1967,2019,OKC,Thunder,1967,Oklahoma City,Chesapeake Energy Arena,19163.0,Clay Bennett,Sam Presti,Billy Donovan,Oklahoma City Blue
22,0,1610612761,1995,2019,TOR,Raptors,1995,Toronto,Scotiabank Arena,19800.0,Maple Leaf Sports and Entertainment,Masai Ujiri,Nick Nurse,Raptors 905
23,0,1610612762,1974,2019,UTA,Jazz,1974,Utah,Vivint Smart Home Arena,20148.0,Greg Miller,Dennis Lindsey,Quin Snyder,Salt Lake City Stars
24,0,1610612763,1995,2019,MEM,Grizzlies,1995,Memphis,FedExForum,18119.0,Robert Pera,Zach Kleiman,Taylor Jenkins,Memphis Hustle
25,0,1610612764,1961,2019,WAS,Wizards,1961,Washington,Capital One Arena,20647.0,Ted Leonsis,Tommy Sheppard,Scott Brooks,Capital City Go-Go
26,0,1610612765,1948,2019,DET,Pistons,1948,Detroit,Little Caesars Arena,21000.0,Tom Gores,Ed Stefanski,Dwane Casey,Grand Rapids Drive
27,0,1610612766,1988,2019,CHA,Hornets,1988,Charlotte,Spectrum Center,19026.0,Michael Jordan,Mitch Kupchak,James Borrego,Greensboro Swarm
28,0,1610612739,1970,2019,CLE,Cavaliers,1970,Cleveland,Quicken Loans Arena,20562.0,Dan Gilbert,Koby Altman,John Beilein,Canton Charge
29,0,1610612744,1946,2019,GSW,Warriors,1946,Golden State,Chase Center,19596.0,Joe Lacob,Bob Myers,Steve Kerr,Santa Cruz Warriors

In [19]:
merge1_df = pd.merge(teams_df,games_df,left_on='TEAM_ID', right_on='HOME_TEAM_ID')
merge1_df.head(2)

,LEAGUE_ID,TEAM_ID,MIN_YEAR,MAX_YEAR,ABBREVIATION,NICKNAME,YEARFOUNDED,CITY,ARENA,ARENACAPACITY,...,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
0,0,1610612737,1949,2019,ATL,Hawks,1949,Atlanta,State Farm Arena,18729.0,...,29.0,61.0,1610612754,135.0,0.459,0.846,0.400,22.0,43.0,0
1,0,1610612737,1949,2019,ATL,Hawks,1949,Atlanta,State Farm Arena,18729.0,...,29.0,44.0,1610612755,122.0,0.459,0.579,0.323,27.0,57.0,1

In [20]:
merge1_df.shape

(2343, 35)

In [23]:
merge2_df = pd.merge(teams_df, games_df,left_on='TEAM_ID', right_on='HOME_TEAM_ID', how='outer')

In [24]:
merge2_df

,LEAGUE_ID,TEAM_ID,MIN_YEAR,MAX_YEAR,ABBREVIATION,NICKNAME,YEARFOUNDED,CITY,ARENA,ARENACAPACITY,...,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
0,0,1610612737,1949,2019,ATL,Hawks,1949,Atlanta,State Farm Arena,18729.0,...,29.0,61.0,1610612754,135.0,0.459,0.846,0.400,22.0,43.0,0
1,0,1610612737,1949,2019,ATL,Hawks,1949,Atlanta,State Farm Arena,18729.0,...,29.0,44.0,1610612755,122.0,0.459,0.579,0.323,27.0,57.0,1
2,0,1610612737,1949,2019,ATL,Hawks,1949,Atlanta,State Farm Arena,18729.0,...,36.0,58.0,1610612749,135.0,0.414,0.957,0.309,30.0,71.0,1
3,0,1610612737,1949,2019,ATL,Hawks,1949,Atlanta,State Farm Arena,18729.0,...,20.0,41.0,1610612757,118.0,0.469,0.864,0.281,19.0,55.0,0
4,0,1610612737,1949,2019,ATL,Hawks,1949,Atlanta,State Farm Arena,18729.0,...,28.0,49.0,1610612755,127.0,0.462,0.846,0.435,21.0,52.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2338,0,1610612744,1946,2019,GSW,Warriors,1946,Golden State,Chase Center,19596.0,...,24.0,43.0,1610612756,121.0,0.458,0.857,0.417,33.0,45.0,0
2339,0,1610612744,1946,2019,GSW,Warriors,1946,Golden State,Chase Center,19596.0,...,27.0,42.0,1610612746,141.0,0.625,0.767,0.563,33.0,39.0,0
2340,0,1610612744,1946,2019,GSW,Warriors,1946,Golden State,Chase Center,19596.0,...,24.0,56.0,1610612747,103.0,0.410,0.667,0.406,25.0,35.0,1
2341,0,1610612744,1946,2019,GSW,Warriors,1946,Golden State,Chase Center,19596.0,...,34.0,50.0,1610612750,123.0,0.407,0.840,0.286,27.0,51.0,1
2342,0,1610612744,1946,2019,GSW,Warriors,1946,Golden State,Chase Center,19596.0,...,20.0,47.0,1610612747,123.0,0.475,0.633,0.303,32.0,58.0,0

In [28]:
players18 = pd.read_csv(r'C:\Users\pad39\Downloads\inclass-data-main\inclass-data-main\2018-players.csv')
players19 = pd.read_csv(r'C:\Users\pad39\Downloads\inclass-data-main\inclass-data-main\2019-players.csv')
players_df = pd.merge(players18,players19,on='PLAYER_ID')
players_df

,Unnamed: 0_x,PLAYER_NAME_x,TEAM_ID_x,PLAYER_ID,SEASON_x,Unnamed: 0_y,PLAYER_NAME_y,TEAM_ID_y,SEASON_y
0,626,Kawhi Leonard,1610612761,202695,2018,299,Kawhi Leonard,1610612746,2019
1,627,Pascal Siakam,1610612761,1627783,2018,275,Pascal Siakam,1610612761,2019
2,628,Marc Gasol,1610612761,201188,2018,276,Marc Gasol,1610612761,2019
3,1157,Marc Gasol,1610612763,201188,2018,276,Marc Gasol,1610612761,2019
4,629,Danny Green,1610612761,201980,2018,202,Danny Green,1610612747,2019
...,...,...,...,...,...,...,...,...,...
533,1339,Abdul Gaddy,1610612760,203583,2018,561,Abdul Gaddy,1610612760,2019
534,1342,Andre Roberson,1610612760,203460,2018,566,Andre Roberson,1610612760,2019
535,1348,Norvel Pelle,1610612755,203658,2018,24,Norvel Pelle,1610612755,2019
536,1350,Denzel Valentine,1610612741,1627756,2018,58,Denzel Valentine,1610612741,2019
537,1353,C.J. Wilcox,1610612754,203912,2018,573,C.J. Wilcox,1610612754,2019